name: InventoryBackup
version: 1.0
main: it.quick.inventorybackup.InventoryBackup
api-version: 1.13
commands:
  inventorybackupper:
    description: "Gestisci gli inventari di backup"
permissions:
  inventorybackupper.interact:
    description: "Permette ai giocatori di interagire con le GUI dei backup e prelevare oggetti."
    default: false
  inventorybackupper.use:
    description: "Permette ai giocatori di usare il comando inventorybackupper loadinv."
    default: false
  inventorybackupper.info:
      description: "Permette ai giocatori di usare il comando inventorybackupper info."
      default: true